name: Python Linter & Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '14'
    - name: Run migrations
      run: pipenv run flask db upgrade
    - name: Test with nose
      run: |
        pipenv run nosetests
